---
- name: Add apt-key
  shell: >
   apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

- name: Add mongodb repo
  apt_repository:
    repo: "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen"
    state: present

- name: Install MongoDB
  apt:
    pkg: "mongodb-org"
    state: present

- name: Ensure MongoDB is running
  service:
    name: mongod
    state: started

- name: Install pymongo if users are to be added.
  apt: >
    pkg={{ item }}
  with_items:
   - python-pymongo
  when: mongodb_users|length > 0